"use client";

import * as React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { FileText, Hash, Calendar, User, Database, ChevronDown, ChevronRight, ChevronLeft } from 'lucide-react';
import { getReportList, downloadReport } from '@/lib/api';
import { Button } from '@/components/ui/button';

interface Lineage {
  row_count?: number;
  date_range?: { start: string; end: string };
  generated_by?: string;
  generated_at?: string;
  content_sha256?: string;
  source?: string;
  machine_id?: string;
  shift?: string;
  report_type?: string;
}

interface Report {
  id: string;
  name: string;
  title: string;
  created_at: string | null;
  status: string;
  filename: string;
  created_by: string;
  lineage: Lineage;
}

function LineagePanel({ lineage }: { lineage: Lineage }) {
  const [open, setOpen] = React.useState(false);
  if (!lineage || Object.keys(lineage).length === 0) return null;
  return (
    <div className="mt-3 border-t pt-3">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors"
      >
        {open ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
        Data Provenance
      </button>
      {open && (
        <dl className="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1.5 text-xs">
          {lineage.row_count !== undefined && (
            <>
              <dt className="flex items-center gap-1 text-muted-foreground"><Database className="h-3 w-3" />Rows</dt>
              <dd className="font-mono">{lineage.row_count.toLocaleString()}</dd>
            </>
          )}
          {lineage.machine_id && (
            <>
              <dt className="text-muted-foreground">Machine</dt>
              <dd>{lineage.machine_id}</dd>
            </>
          )}
          {lineage.shift && (
            <>
              <dt className="text-muted-foreground">Shift</dt>
              <dd>{lineage.shift}</dd>
            </>
          )}
          {lineage.date_range && (
            <>
              <dt className="flex items-center gap-1 text-muted-foreground"><Calendar className="h-3 w-3" />Date range</dt>
              <dd>{lineage.date_range.start} → {lineage.date_range.end}</dd>
            </>
          )}
          {lineage.generated_by && (
            <>
              <dt className="flex items-center gap-1 text-muted-foreground"><User className="h-3 w-3" />Generated by</dt>
              <dd>{lineage.generated_by}</dd>
            </>
          )}
          {lineage.content_sha256 && (
            <>
              <dt className="flex items-center gap-1 text-muted-foreground col-span-1"><Hash className="h-3 w-3" />SHA-256</dt>
              <dd className="font-mono break-all text-[10px] col-span-1">{lineage.content_sha256}</dd>
            </>
          )}
        </dl>
      )}
    </div>
  );
}

export default function ReportHistoryPage() {
  const [reports, setReports] = React.useState<Report[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [downloading, setDownloading] = React.useState<string | null>(null);
  const [page, setPage] = React.useState(1);
  const PAGE_SIZE = 20;

  React.useEffect(() => {
    getReportList()
      .then((res) => {
        setReports(res.data);
        setLoading(false);
      })
      .catch(() => {
        setError('Failed to load reports');
        setLoading(false);
      });
  }, []);

  const handleDownload = async (reportId: string, filename: string) => {
    setDownloading(reportId);
    try {
      // Backend /report/download/{file_name} expects the filename, not the DB row id.
      const res = await downloadReport(filename);
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', filename || `report_${reportId}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
      window.URL.revokeObjectURL(url);
    } finally {
      setDownloading(null);
    }
  };

  return (
    <div className="container mx-auto py-8">
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="flex items-center text-2xl font-bold">
            <FileText className="mr-3 h-7 w-7 text-primary" />
            Report History
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground mb-4">
            View and download previously generated reports. Expand a report to inspect its data provenance.
          </p>
          {loading ? (
            <div className="text-center py-8">Loading reports...</div>
          ) : error ? (
            <div className="text-center text-destructive py-8">{error}</div>
          ) : reports.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">No reports found.</div>
          ) : (
            <>
            <ul className="space-y-3">
              {reports.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE).map((report) => (
                <li key={report.id} className="border rounded-lg p-4 bg-card">
                  <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-semibold text-base">{report.name || report.title || `Report #${report.id}`}</span>
                        <Badge variant={report.status === 'success' ? 'default' : 'destructive'} className="text-xs">
                          {report.status}
                        </Badge>
                      </div>
                      <div className="mt-1 flex flex-wrap gap-x-4 gap-y-0.5 text-xs text-muted-foreground">
                        <span>ID: {report.id}</span>
                        {report.created_by && <span><User className="inline h-3 w-3 mr-0.5" />{report.created_by}</span>}
                        {report.created_at && (
                          <span><Calendar className="inline h-3 w-3 mr-0.5" />{new Date(report.created_at).toLocaleString()}</span>
                        )}
                        {report.lineage?.row_count !== undefined && (
                          <span><Database className="inline h-3 w-3 mr-0.5" />{report.lineage.row_count.toLocaleString()} rows</span>
                        )}
                      </div>
                      <LineagePanel lineage={report.lineage} />
                    </div>
                    <Button
                      size="sm"
                      className="shrink-0"
                      onClick={() => handleDownload(report.id, report.filename || `report_${report.id}.pdf`)}
                      disabled={downloading === report.id}
                    >
                      {downloading === report.id ? 'Downloading…' : 'Download'}
                    </Button>
                  </div>
                </li>
              ))}
            </ul>
            {reports.length > PAGE_SIZE && (
              <div className="flex items-center justify-between pt-4 text-sm text-muted-foreground">
                <span>{reports.length} reports · page {page} of {Math.ceil(reports.length / PAGE_SIZE)}</span>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1}>
                    <ChevronLeft className="h-4 w-4" />
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setPage((p) => Math.min(Math.ceil(reports.length / PAGE_SIZE), p + 1))} disabled={page >= Math.ceil(reports.length / PAGE_SIZE)}>
                    <ChevronRight className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
