import logging
logging.basicConfig(level=logging.DEBUG)
from fpdf import FPDF
import os

class PDF(FPDF):
    def header(self):
        self.set_fill_color(30, 136, 229) # #1E88E5
        self.rect(0, 0, 210, 25, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 18)
        self.text(10, 12, "SCADA ASSISTANT")
        self.set_font("helvetica", "", 9)
        self.text(10, 18, "AUTOMATED PERFORMANCE & TELEMETRY REPORT")
        self.set_y(30)

    def footer(self):
        self.set_y(-15)
        self.set_draw_color(224, 224, 224)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_text_color(128, 128, 128)
        self.set_font("helvetica", "", 8)
        self.cell(0, 10, "CONFIDENTIAL - AUTOMATICALLY GENERATED BY SCADA REPORT ENGINE", 0, 0, "L")

pdf = PDF()
pdf.add_page()
html = """
<h1>Machine Performance Report</h1>
<table border="1" width="100%">
    <thead>
        <tr><th>Timestamp</th><th>Value</th></tr>
    </thead>
    <tbody>
        <tr><td>2026-01-01 10:00:00</td><td>45.5</td></tr>
    </tbody>
</table>
"""
pdf.write_html(html)
pdf.output("test.pdf")
print("PDF created")
